export type CapabilitySurface =
  | "Home"
  | "Chat"
  | "History"
  | "Day Detail"
  | "Meal Edit"
  | "Settings"
  | "onboarding"
  | "guest recovery";

export type CapabilitySupportState =
  | "supported"
  | "supported-read-only"
  | "inert-honest-placeholder"
  | "hidden-future-scope"
  | "repair-needed";

export type CapabilityPlaceholderShape = "button" | "row" | "card" | "none";

export type CapabilityRequirementId = "ALIGN-01" | "ALIGN-02" | "ALIGN-03" | "ALIGN-04";

export type CapabilitySeverity = "none" | "blocker" | "must-fix" | "follow-up";

export interface CapabilityMatrixRow {
  readonly surface: CapabilitySurface;
  readonly affordance: string;
  readonly sourceFile: string;
  readonly sourceMatchers: readonly string[];
  readonly handlerMatchers?: readonly string[];
  readonly supportState: CapabilitySupportState;
  readonly placeholderShape: CapabilityPlaceholderShape;
  readonly clientApi: readonly string[];
  readonly storeAction: readonly string[];
  readonly backendRoute: readonly string[];
  readonly backendService: readonly string[];
  readonly handlingDecision: string;
  readonly requirements: readonly CapabilityRequirementId[];
  readonly testCoverage: readonly string[];
  readonly visibleCopy: string | null;
  readonly disabledEvidence: readonly string[];
  readonly futurePhaseRef: string | null;
  readonly severity: CapabilitySeverity;
  readonly activeHandler: "present" | "none";
}

export const capabilityMatrix = [
  {
    surface: "Home",
    affordance: "Coach CTA prompt handoff to Chat",
    sourceFile: "client/src/components/HomeScreen.tsx",
    sourceMatchers: ["sendHomeCtaTaskOption", "stageHomeTaskOptionPrompt", "setActiveScreen(\"chat\")"],
    handlerMatchers: ["sendHomeCtaTaskOption", "onEmptyChatClick"],
    supportState: "supported",
    placeholderShape: "none",
    clientApi: ["recordHomeCtaIntentSelected", "recordHomeCtaOptionSent"],
    storeAction: ["setPendingHomeChatDraft", "setActiveScreen(\"chat\")"],
    backendRoute: [],
    backendService: [],
    handlingDecision: "Home may stage supported prompts only when the flow lands in Chat through the existing draft and tab actions.",
    requirements: ["ALIGN-01", "ALIGN-02"],
    testCoverage: ["tests/unit/capability-matrix-contract.test.ts"],
    visibleCopy: "去對話記錄",
    disabledEvidence: [],
    futurePhaseRef: null,
    severity: "none",
    activeHandler: "present",
  },
  {
    surface: "Home",
    affordance: "Today meal rows and authorized thumbnails",
    sourceFile: "client/src/components/HomeScreen.tsx",
    sourceMatchers: ["MealRows", "home-sport-meal-row", "buildMealEditPayloadIfComplete", "openMealEdit(editPayload, \"home\")"],
    handlerMatchers: ["openMealEdit(editPayload, \"home\")"],
    supportState: "supported",
    placeholderShape: "row",
    clientApi: ["getMeals", "withAuthorizedAssetUrl"],
    storeAction: ["openMealEdit"],
    backendRoute: ["/api/meals", "/api/assets/:id"],
    backendService: ["createFoodLoggingService", "readOwnedAsset"],
    handlingDecision: "Home opens eligible complete meals through the existing Meal Edit surface and leaves incomplete rows read-only; grouped meals use Meal Edit item rows when authoritative details are present.",
    requirements: ["ALIGN-01", "ALIGN-03"],
    testCoverage: ["tests/unit/capability-matrix-contract.test.ts"],
    visibleCopy: "今日紀錄",
    disabledEvidence: [],
    futurePhaseRef: "Meal Image Continuity",
    severity: "none",
    activeHandler: "present",
  },
  {
    surface: "Home",
    affordance: "Settings navigation",
    sourceFile: "client/src/components/HomeScreen.tsx",
    sourceMatchers: ["openSecondaryScreen(\"settings\", \"home\")", "disabled={sending}", "aria-label=\"設定\""],
    handlerMatchers: ["openSecondaryScreen(\"settings\", \"home\")"],
    supportState: "supported",
    placeholderShape: "button",
    clientApi: [],
    storeAction: ["openSecondaryScreen"],
    backendRoute: [],
    backendService: [],
    handlingDecision: "Home settings navigation may stay active only as the existing secondary-screen transition into supported Settings rows.",
    requirements: ["ALIGN-01", "ALIGN-03"],
    testCoverage: ["tests/unit/capability-matrix-contract.test.ts", "tests/unit/capability-matrix-source-scan.test.ts"],
    visibleCopy: "設定",
    disabledEvidence: ["disabled={sending}"],
    futurePhaseRef: null,
    severity: "none",
    activeHandler: "present",
  },
  {
    surface: "Chat",
    affordance: "Text/photo meal logging with SSE progress",
    sourceFile: "client/src/components/ChatPanel.tsx",
    sourceMatchers: [
      "sendMessageStream",
      "setProvisionalStatus",
      "commitProvisionalBubble",
      "sendPendingDraft",
      "clearPendingHomeChatDraft",
      "CHAT_EMPTY_STARTER_PROMPTS",
      "handleStarterPromptClick",
    ],
    handlerMatchers: ["sendPendingDraft", "handleStarterPromptClick"],
    supportState: "supported",
    placeholderShape: "none",
    clientApi: ["sendMessageStream", "sendMessage", "withAuthorizedAssetUrl"],
    storeAction: ["setDailyTargets", "setPendingHomeChatDraft"],
    backendRoute: ["/api/chat", "/api/assets/:id"],
    backendService: ["createDurableAssetIfNeeded", "createChatService"],
    handlingDecision: "Chat remains the primary route-backed logging flow for text, photo upload, streaming status, receipts, and target updates.",
    requirements: ["ALIGN-01", "ALIGN-02", "ALIGN-03"],
    testCoverage: ["tests/unit/capability-matrix-contract.test.ts"],
    visibleCopy: "送出訊息",
    disabledEvidence: [],
    futurePhaseRef: null,
    severity: "none",
    activeHandler: "present",
  },
  {
    surface: "Chat",
    affordance: "In-progress generation stop",
    sourceFile: "client/src/components/ChatPanel.tsx",
    sourceMatchers: ["handleStopStreaming", "stopChatTurn", "commitStoppedProvisionalBubble", "onStop={handleStopStreaming}"],
    handlerMatchers: ["handleStopStreaming"],
    supportState: "supported",
    placeholderShape: "none",
    clientApi: ["stopChatTurn", "sendMessageStream"],
    storeAction: ["commitStoppedProvisionalBubble", "setProvisionalStatus"],
    backendRoute: ["/api/chat/stop"],
    backendService: ["createChatService"],
    handlingDecision: "Chat Stop is now a supported graceful side-channel action that preserves the active stream until the stopped terminal event settles UI state.",
    requirements: ["ALIGN-01", "ALIGN-03"],
    testCoverage: [
      "tests/unit/capability-matrix-source-scan.test.ts",
      "tests/unit/chat-stream-contract.test.ts",
    ],
    visibleCopy: "停止生成",
    disabledEvidence: ["stopDisabled={stopping || !activeTurnId}"],
    futurePhaseRef: null,
    severity: "none",
    activeHandler: "present",
  },
  {
    surface: "Chat",
    affordance: "Composer send and photo attachment",
    sourceFile: "client/src/components/ChatInput.tsx",
    sourceMatchers: [
      "onSubmit={handleSubmit}",
      "submitMessage",
      "fileRef.current?.click()",
      "handleImageChange",
      "getSupportedImageMimeType",
      "setImage(null)",
      "SportStopIcon",
      "aria-label=\"停止生成\"",
      "onClick={onStop}",
    ],
    handlerMatchers: [
      "onSubmit={handleSubmit}",
      "submitMessage",
      "fileRef.current?.click()",
      "handleImageChange",
      "setImage(null)",
      "onClick={onStop}",
      "handleKeyDown",
    ],
    supportState: "supported",
    placeholderShape: "none",
    clientApi: ["sendMessageStream"],
    storeAction: [],
    backendRoute: ["/api/chat"],
    backendService: ["createChatService"],
    handlingDecision: "The composer may submit text/photo payloads only through ChatPanel's supported streaming send path.",
    requirements: ["ALIGN-01", "ALIGN-02", "ALIGN-03"],
    testCoverage: ["tests/unit/capability-matrix-contract.test.ts", "tests/unit/capability-matrix-source-scan.test.ts"],
    visibleCopy: "送出",
    disabledEvidence: [],
    futurePhaseRef: null,
    severity: "none",
    activeHandler: "present",
  },
  {
    surface: "Chat",
    affordance: "Meal receipt edit handoff",
    sourceFile: "client/src/components/MessageBubble.tsx",
    sourceMatchers: [
      "handleOpenReceipt",
      "onClick={canEdit ? handleOpenReceipt : undefined}",
      "onKeyDown={canEdit ? handleReceiptKeyDown : undefined}",
      "role={canEdit ? \"button\" : undefined}",
      "onOpenMealEdit?.(editPayload)",
    ],
    handlerMatchers: [
      "handleOpenReceipt",
      "handleReceiptKeyDown",
      "onClick={canEdit ? handleOpenReceipt : undefined}",
      "onKeyDown={canEdit ? handleReceiptKeyDown : undefined}",
    ],
    supportState: "supported",
    placeholderShape: "card",
    clientApi: [],
    storeAction: ["openMealEdit"],
    backendRoute: [],
    backendService: [],
    handlingDecision: "Receipt cards may expose edit only by opening the existing Meal Edit state boundary.",
    requirements: ["ALIGN-01", "ALIGN-03"],
    testCoverage: ["tests/unit/capability-matrix-contract.test.ts"],
    visibleCopy: "編輯餐點",
    disabledEvidence: [],
    futurePhaseRef: null,
    severity: "none",
    activeHandler: "present",
  },
  {
    surface: "History",
    affordance: "Trend and day browsing",
    sourceFile: "client/src/components/HistoryScreen.tsx",
    sourceMatchers: [
      "getHistoryTrends",
      "getHistoryDaySnapshot",
      "openDayDetail",
      "onSelect(day.dateKey)",
      "onTimelineOpen()",
      "targetMealId: meal.id",
      "onMealOpen(meal)",
      "開啟餐點詳情",
      "moveWeek",
      "getHistoryWeekHeaderLabel",
      "openConfirmedEmptyDayDetail",
    ],
    handlerMatchers: ["onSelect(day.dateKey)", "onTimelineOpen()", "handleTimelineKeyDown", "onMealOpen(meal)", "openConfirmedEmptyDayDetail", "moveWeek"],
    supportState: "supported-read-only",
    placeholderShape: "card",
    clientApi: ["getHistoryTrends", "getHistoryDaySnapshot"],
    storeAction: ["openDayDetail"],
    backendRoute: ["/api/history/trends", "/api/history/days/:date"],
    backendService: ["createHistoryQueryService"],
    handlingDecision: "History is supported as read-only trend, day, and meal evidence browsing; meal rows open focused Day Detail with targetMealId.",
    requirements: ["ALIGN-01", "ALIGN-02"],
    testCoverage: ["tests/unit/capability-matrix-contract.test.ts"],
    visibleCopy: "歷史紀錄",
    disabledEvidence: [],
    futurePhaseRef: null,
    severity: "none",
    activeHandler: "present",
  },
  {
    surface: "History",
    affordance: "Weekly AI insights",
    sourceFile: "client/src/components/HistoryScreen.tsx",
    sourceMatchers: ["HistoryStatGrid", "TimelinePanel", "getHistoryTrends"],
    supportState: "hidden-future-scope",
    placeholderShape: "none",
    clientApi: [],
    storeAction: [],
    backendRoute: [],
    backendService: [],
    handlingDecision: "Productized weekly recommendations are not part of Phase 44 or v2.0 capability alignment.",
    requirements: ["ALIGN-04"],
    testCoverage: ["tests/unit/capability-matrix-contract.test.ts"],
    visibleCopy: null,
    disabledEvidence: [],
    futurePhaseRef: "Insights",
    severity: "none",
    activeHandler: "none",
  },
  {
    surface: "Day Detail",
    affordance: "Read-only day snapshot",
    sourceFile: "client/src/components/HistoryDayDetailScreen.tsx",
    sourceMatchers: [
      "getHistoryDaySnapshot",
      "payloadLabel",
      "歷史快照",
      "buildMealEditPayloadIfComplete",
      "targetMealId",
      "openMealEdit",
      "returnToDayDetail",
      "編輯餐點：",
    ],
    handlerMatchers: ["onClick={onBack}", "onClick={onEdit}", "openMealEdit(editPayload, \"history\""],
    supportState: "supported-read-only",
    placeholderShape: "card",
    clientApi: ["getHistoryDaySnapshot", "withAuthorizedAssetUrl"],
    storeAction: ["openMealEdit"],
    backendRoute: ["/api/history/days/:date", "/api/assets/:id"],
    backendService: ["createHistoryQueryService", "readOwnedAsset"],
    handlingDecision: "Historical day detail is snapshot browsing with a focused eligible edit handoff; delete remains in Meal Edit.",
    requirements: ["ALIGN-01", "ALIGN-03"],
    testCoverage: ["tests/unit/capability-matrix-contract.test.ts"],
    visibleCopy: "每日摘要",
    disabledEvidence: [],
    futurePhaseRef: null,
    severity: "none",
    activeHandler: "present",
  },
  {
    surface: "Meal Edit",
    affordance: "Update meal nutrition and image reference",
    sourceFile: "client/src/components/MealEditScreen.tsx",
    sourceMatchers: ["updateMeal", "handleSave", "recordMealMutation", "setMeals"],
    handlerMatchers: ["handleSave", "setDraft({ ...draft, foodName", "setDraft({ ...draft, [field.key]"],
    supportState: "supported",
    placeholderShape: "none",
    clientApi: ["updateMeal", "withAuthorizedAssetUrl"],
    storeAction: ["recordMealMutation", "setMeals"],
    backendRoute: ["/api/meals/:id", "/api/assets/:id"],
    backendService: ["updateMeal", "getOwnedAsset"],
    handlingDecision: "Meal save is active only through the existing PATCH route and mutation refresh path.",
    requirements: ["ALIGN-01", "ALIGN-02", "ALIGN-03"],
    testCoverage: ["tests/unit/capability-matrix-contract.test.ts"],
    visibleCopy: "儲存餐點",
    disabledEvidence: [],
    futurePhaseRef: null,
    severity: "none",
    activeHandler: "present",
  },
  {
    surface: "Meal Edit",
    affordance: "Delete meal",
    sourceFile: "client/src/components/MealEditScreen.tsx",
    sourceMatchers: ["deleteMeal", "handleDelete", "recordMealMutation"],
    handlerMatchers: ["handleDelete"],
    supportState: "supported",
    placeholderShape: "button",
    clientApi: ["deleteMeal"],
    storeAction: ["removeMeal", "recordMealMutation"],
    backendRoute: ["/api/meals/:id"],
    backendService: ["deleteMeal"],
    handlingDecision: "Meal delete is active only through the existing DELETE route and local meal removal action.",
    requirements: ["ALIGN-01", "ALIGN-03"],
    testCoverage: ["tests/unit/capability-matrix-contract.test.ts"],
    visibleCopy: "刪除餐點",
    disabledEvidence: [],
    futurePhaseRef: null,
    severity: "none",
    activeHandler: "present",
  },
  {
    surface: "Meal Edit",
    affordance: "Meal image display",
    sourceFile: "client/src/components/MealEditScreen.tsx",
    sourceMatchers: ["imageAssetId", "imageUrl", "PersistedAssetImage"],
    handlerMatchers: ["openMealEdit"],
    supportState: "supported-read-only",
    placeholderShape: "card",
    clientApi: ["withAuthorizedAssetUrl"],
    storeAction: [],
    backendRoute: ["/api/assets/:id"],
    backendService: ["readOwnedAsset"],
    handlingDecision: "Meal Edit may display an existing authorized meal image reference; Phase 46 owns deeper continuity repairs.",
    requirements: ["ALIGN-03"],
    testCoverage: ["tests/unit/capability-matrix-contract.test.ts"],
    visibleCopy: "餐點照片",
    disabledEvidence: [],
    futurePhaseRef: "Meal Image Continuity",
    severity: "none",
    activeHandler: "present",
  },
  {
    surface: "Meal Edit",
    affordance: "Grouped item editing",
    sourceFile: "client/src/components/MealEditScreen.tsx",
    sourceMatchers: [
      "payload.itemCount > 1",
      "GroupedMealEditor",
      "sp-meal-edit-grouped-row",
      "buildGroupedMealUpdateItems",
      "新增項目",
    ],
    handlerMatchers: [
      "onToggle(index)",
      "onDelete(index)",
      "onChange(index,",
      "onChange={onChange}",
      "handleGroupedExit",
      "handleGroupedAddItem",
      "handleSave",
    ],
    supportState: "supported",
    placeholderShape: "card",
    clientApi: ["updateMeal"],
    storeAction: ["recordMealMutation", "setMeals"],
    backendRoute: ["/api/meals/:id"],
    backendService: ["updateMeal"],
    handlingDecision: "Grouped Meal Edit submits a complete ordered items[] list through the existing revision-safe PATCH route, while unsupported grouped payloads remain non-editable.",
    requirements: ["ALIGN-01", "ALIGN-02", "ALIGN-03"],
    testCoverage: ["tests/unit/capability-matrix-contract.test.ts", "tests/unit/capability-matrix-source-scan.test.ts"],
    visibleCopy: "新增項目",
    disabledEvidence: [],
    futurePhaseRef: null,
    severity: "none",
    activeHandler: "present",
  },
  {
    surface: "Settings",
    affordance: "Daily target editing",
    sourceFile: "client/src/components/GoalSettings.tsx",
    sourceMatchers: ["startEditing", "handleCancel", "updateGoals(form)", "setDailyTargets(updated)", "儲存"],
    handlerMatchers: ["startEditing", "handleCancel", "handleSave", "normalizeTargetInputValue"],
    supportState: "supported",
    placeholderShape: "none",
    clientApi: ["updateGoals"],
    storeAction: ["setDailyTargets"],
    backendRoute: ["/api/device/goals"],
    backendService: ["updateGoals"],
    handlingDecision: "Settings can edit only daily macro targets through the supported guest-session-backed goal route.",
    requirements: ["ALIGN-01", "ALIGN-02", "ALIGN-03"],
    testCoverage: ["tests/unit/capability-matrix-contract.test.ts"],
    visibleCopy: "儲存",
    disabledEvidence: [],
    futurePhaseRef: null,
    severity: "none",
    activeHandler: "present",
  },
  {
    surface: "Settings",
    affordance: "Reminder and advanced settings",
    sourceFile: "client/src/components/GoalSettings.tsx",
    sourceMatchers: ["提醒", "尚未開放", "SettingsRow"],
    supportState: "inert-honest-placeholder",
    placeholderShape: "row",
    clientApi: [],
    storeAction: [],
    backendRoute: [],
    backendService: [],
    handlingDecision: "Reminder, timezone, language, and advanced settings rows must remain passive until a later settings capability exists.",
    requirements: ["ALIGN-04"],
    testCoverage: ["tests/unit/capability-matrix-contract.test.ts"],
    visibleCopy: "尚未開放",
    disabledEvidence: ["aria-disabled=\"true\"", "disabled"],
    futurePhaseRef: "Mobile Shell and Chat Control Stability",
    severity: "none",
    activeHandler: "none",
  },
  {
    surface: "Settings",
    affordance: "Export data",
    sourceFile: "client/src/components/GoalSettings.tsx",
    sourceMatchers: ["匯出資料", "尚未開放"],
    supportState: "inert-honest-placeholder",
    placeholderShape: "row",
    clientApi: [],
    storeAction: [],
    backendRoute: [],
    backendService: [],
    handlingDecision: "Export controls are visible only as unavailable data-management placeholders.",
    requirements: ["ALIGN-04"],
    testCoverage: ["tests/unit/capability-matrix-contract.test.ts"],
    visibleCopy: "尚未開放",
    disabledEvidence: ["aria-disabled=\"true\"", "disabled"],
    futurePhaseRef: "Identity and Continuity",
    severity: "none",
    activeHandler: "none",
  },
  {
    surface: "Settings",
    affordance: "Backup and restore",
    sourceFile: "client/src/components/GoalSettings.tsx",
    sourceMatchers: ["資料管理", "尚未開放"],
    supportState: "inert-honest-placeholder",
    placeholderShape: "row",
    clientApi: [],
    storeAction: [],
    backendRoute: [],
    backendService: [],
    handlingDecision: "Backup and restore are future identity/data-continuity capabilities and cannot appear active.",
    requirements: ["ALIGN-04"],
    testCoverage: ["tests/unit/capability-matrix-contract.test.ts"],
    visibleCopy: "尚未開放",
    disabledEvidence: ["aria-disabled=\"true\"", "disabled"],
    futurePhaseRef: "Identity and Continuity",
    severity: "none",
    activeHandler: "none",
  },
  {
    surface: "Settings",
    affordance: "Account linking",
    sourceFile: "client/src/components/GoalSettings.tsx",
    sourceMatchers: ["訪客模式", "使用中"],
    supportState: "hidden-future-scope",
    placeholderShape: "none",
    clientApi: [],
    storeAction: [],
    backendRoute: [],
    backendService: [],
    handlingDecision: "Account linking is intentionally omitted from the guest-mode settings surface.",
    requirements: ["ALIGN-04"],
    testCoverage: ["tests/unit/capability-matrix-contract.test.ts"],
    visibleCopy: null,
    disabledEvidence: [],
    futurePhaseRef: "Identity and Continuity",
    severity: "none",
    activeHandler: "none",
  },
  {
    surface: "onboarding",
    affordance: "Intake submission",
    sourceFile: "client/src/components/onboarding/OnboardingStepper.tsx",
    sourceMatchers: [
      "submitIntake",
      "setDevice",
      "繼續 →",
      "onAdd",
      "onRemove",
      "onSelect?.",
      "set(\"sex\"",
      "set(\"age\"",
      "set(\"heightCm\"",
      "set(\"weightKg\"",
      "set(\"activityLevel\"",
      "set(\"trainingFrequency\"",
      "onAdvancedMetricsNext",
      "onAdvancedMetricsSkip",
      "onRetry",
      "onFieldEdit",
      "setGoalClarification",
      "setBodyData",
      "setLifestyle",
      "setAdvanced",
    ],
    handlerMatchers: [
      "submitIntake",
      "onBack",
      "onNext",
      "onAdd",
      "onRemove",
      "onSelect?.",
      "set(\"sex\"",
      "set(\"age\"",
      "set(\"heightCm\"",
      "set(\"weightKg\"",
      "set(\"activityLevel\"",
      "set(\"trainingFrequency\"",
      "onAdvancedMetricsNext",
      "onAdvancedMetricsSkip",
      "onRetry",
      "onFieldEdit",
      "setGoalClarification",
      "setBodyData",
      "setLifestyle",
      "setAdvanced",
      "startDrag",
      "onChange?.(String(item.value))",
    ],
    supportState: "supported",
    placeholderShape: "none",
    clientApi: ["submitIntake", "registerDevice"],
    storeAction: ["setDevice"],
    backendRoute: ["/api/device"],
    backendService: ["createDevice", "generateTargets"],
    handlingDecision: "Onboarding may create a guest device and generated targets through the existing intake route.",
    requirements: ["ALIGN-01", "ALIGN-02", "ALIGN-03"],
    testCoverage: ["tests/unit/capability-matrix-contract.test.ts"],
    visibleCopy: "開始使用",
    disabledEvidence: [],
    futurePhaseRef: null,
    severity: "none",
    activeHandler: "present",
  },
  {
    surface: "onboarding",
    affordance: "Guest-session bootstrap",
    sourceFile: "client/src/store.ts",
    sourceMatchers: ["bootstrapGuestSession", "establishGuestSession", "legacyDeviceId"],
    handlerMatchers: [],
    supportState: "supported",
    placeholderShape: "none",
    clientApi: ["establishGuestSession"],
    storeAction: ["bootstrapGuestSession", "recoverGuestSession"],
    backendRoute: ["/api/device/session"],
    backendService: ["createGuestSessionService", "resolveGuestSession"],
    handlingDecision: "Same-browser guest bootstrap and legacy migration are supported through signed guest-session cookies.",
    requirements: ["ALIGN-01", "ALIGN-03"],
    testCoverage: ["tests/unit/capability-matrix-contract.test.ts"],
    visibleCopy: "訪客模式",
    disabledEvidence: [],
    futurePhaseRef: null,
    severity: "none",
    activeHandler: "present",
  },
  {
    surface: "onboarding",
    affordance: "Account restore and cross-device continuity",
    sourceFile: "client/src/components/onboarding/OnboardingStepper.tsx",
    sourceMatchers: ["SpObHeader", "submitIntake", "setDevice"],
    supportState: "hidden-future-scope",
    placeholderShape: "none",
    clientApi: [],
    storeAction: [],
    backendRoute: [],
    backendService: [],
    handlingDecision: "Onboarding must not promise account login, restore, backup, or cross-device continuity in Phase 44.",
    requirements: ["ALIGN-04"],
    testCoverage: ["tests/unit/capability-matrix-contract.test.ts"],
    visibleCopy: null,
    disabledEvidence: [],
    futurePhaseRef: "Identity and Continuity",
    severity: "none",
    activeHandler: "none",
  },
  {
    surface: "guest recovery",
    affordance: "Rebuild guest diary",
    sourceFile: "client/src/components/GuestSessionRecoveryGate.tsx",
    sourceMatchers: ["rebuildGuestSession", "重新建立訪客日記", "disabled={rebuilding}"],
    handlerMatchers: ["handleRebuild", "rebuildGuestSession"],
    supportState: "supported",
    placeholderShape: "button",
    clientApi: ["clearGuestSession"],
    storeAction: ["rebuildGuestSession"],
    backendRoute: ["/api/device/session"],
    backendService: ["clearGuestSessionCookies"],
    handlingDecision: "Guest recovery exposes only a rebuild CTA that clears the current guest session and returns to onboarding.",
    requirements: ["ALIGN-01", "ALIGN-02", "ALIGN-03"],
    testCoverage: ["tests/unit/capability-matrix-contract.test.ts"],
    visibleCopy: "重新建立訪客日記",
    disabledEvidence: ["disabled={rebuilding}"],
    futurePhaseRef: null,
    severity: "none",
    activeHandler: "present",
  },
  {
    surface: "guest recovery",
    affordance: "Export original records",
    sourceFile: "client/src/components/GuestSessionRecoveryGate.tsx",
    sourceMatchers: ["先匯出原始紀錄", "目前不支援從這個畫面匯出原始紀錄", "aria-disabled=\"true\""],
    supportState: "inert-honest-placeholder",
    placeholderShape: "button",
    clientApi: [],
    storeAction: [],
    backendRoute: [],
    backendService: [],
    handlingDecision: "Recovery may show export only as an honest disabled placeholder because no account/export path exists.",
    requirements: ["ALIGN-04"],
    testCoverage: ["tests/unit/capability-matrix-contract.test.ts"],
    visibleCopy: "尚未開放 - 先匯出原始紀錄",
    disabledEvidence: ["aria-disabled=\"true\"", "disabled"],
    futurePhaseRef: "Identity and Continuity",
    severity: "none",
    activeHandler: "none",
  },
  {
    surface: "guest recovery",
    affordance: "Cross-device continuity",
    sourceFile: "client/src/components/GuestSessionRecoveryGate.tsx",
    sourceMatchers: ["這個瀏覽器", "工作階段", "重新建立"],
    supportState: "hidden-future-scope",
    placeholderShape: "none",
    clientApi: [],
    storeAction: [],
    backendRoute: [],
    backendService: [],
    handlingDecision: "Guest recovery stays same-browser and rebuild-only; cross-device continuity remains future scope.",
    requirements: ["ALIGN-04"],
    testCoverage: ["tests/unit/capability-matrix-contract.test.ts"],
    visibleCopy: null,
    disabledEvidence: [],
    futurePhaseRef: "Identity and Continuity",
    severity: "none",
    activeHandler: "none",
  },
] as const satisfies readonly CapabilityMatrixRow[];
